version: '3.4'

services:
# ==== for unit test to run inside compose ====
    integrationtests:
        build:
            context: .
            dockerfile: Selenium-Docker-Example/Dockerfile
        environment:
            - IS_INTEGRATION_TEST=true
            - SELENIUM_HUB_URL=http://selenium:4444/wd/hub
        depends_on:
            - selenium
